# Databricks notebook source

# ════════════════════════════════════════════════════════════════════════════
# NOTEBOOK: 04_serve_rag_app.py
# MISSION:  medtech-research — Medical Research Discovery
# STATUS:   BROKEN — Wrong app entry point path
# ════════════════════════════════════════════════════════════════════════════
#
# OBJECTIVE:
#   Deploy the Streamlit RAG app (app.py) as a Databricks App. The app is
#   declared in databricks.yml with source_code_path: ./app, which tells
#   DAB to package the local `app.py` file (and any sibling files) as
#   the app's source code.
#
# WHAT YOU'LL LEARN:
#   ✅ Databricks Apps deployment via DAB
#   ✅ app.py entry point convention (must be at the bundle root)
#   ✅ Environment variables passed from DAB to the app
#   ✅ How to verify the app is running and accepting requests
#
# ⚠️ KNOWN BUG:
#   The DAB bundle's `apps.medtech_rag_app.source_code_path` is set to
#   `./src/app.py` (a nested subdirectory path), but Streamlit apps expect
#   `app.py` at the bundle root. The deploy will fail with
#   "Could not find app entry point: app.py".
#
# DATABRICKS APPS:
#   - Apps are containerized web apps hosted by Databricks
#   - The entry point must be named `app.py` and live at the root of
#     `source_code_path`
#   - Free Edition allows 3 apps per account, auto-stop after 24h
# ════════════════════════════════════════════════════════════════════════════

# COMMAND ----------

catalog = spark.conf.get("catalog_name", "main")
schema_prefix = spark.conf.get("schema_prefix", "dbsword_medtech")
app_name = f"medtech-rag-{schema_prefix}"

# COMMAND ----------

# ────────────────────────────────────────────────────────────────────────────
# SECTION 1: Inspect the bundle yml to find the configured source_code_path
# ────────────────────────────────────────────────────────────────────────────
# The DAB yml was generated by bundle.ts. We read it to confirm the path.

import yaml
import os

# Find the bundle directory (created by `databricks bundle deploy` in deployment.ts)
bundle_path = f"/Workspace/Users/{spark.sql('SELECT current_user()').collect()[0][0]}/dbsword-fo-medtech-research"

try:
    with open(f"{bundle_path}/databricks.yml", "r") as f:
        bundle_yml = yaml.safe_load(f)
    configured_path = bundle_yml["resources"]["apps"]["medtech_rag_app"]["source_code_path"]
    print(f"📄 Configured source_code_path: {configured_path}")
except Exception as e:
    print(f"❌ Could not read bundle yml: {e}")
    raise

# COMMAND ----------

# ────────────────────────────────────────────────────────────────────────────
# SECTION 2: Verify app.py exists at the configured path
# ────────────────────────────────────────────────────────────────────────────
# Streamlit apps must have `app.py` at the root of source_code_path.
#
# ⚠️ BUG: If configured_path is './src/app.py', the file exists at
# $bundle_path/src/app.py — but the app runtime expects it at
# $bundle_path/app.py (the source_code_path itself is the root).

app_path = f"{bundle_path}/{configured_path.lstrip('./')}"
print(f"🔍 Looking for app.py at: {app_path}")

import os
if os.path.isfile(app_path):
    print(f"✅ Found app.py at {app_path}")
else:
    print(f"❌ app.py NOT found at {app_path}")
    print("   HINT: The source_code_path in databricks.yml is wrong.")
    print("         It should be './app' (a directory containing app.py at its root),")
    print("         NOT './src/app.py' (a path pointing directly to the file).")
    print()
    print("         Edit src/content/field-ops/medtech-research/bundle/databricks.yml")
    print("         and change `source_code_path: ./src/app.py` to `source_code_path: ./app`")
    print("         Then re-run the deploy command in your terminal:")
    print(f"           databricks bundle deploy --target dev --var catalog={catalog} --var schema_prefix={schema_prefix}")

# COMMAND ----------

# ────────────────────────────────────────────────────────────────────────────
# SECTION 3: Wait for the app to come online
# ────────────────────────────────────────────────────────────────────────────
# After fixing the yml and re-deploying, the app should be running within
# 1-2 minutes. We poll the apps API to confirm.

from databricks.sdk import WorkspaceClient
import time

w = WorkspaceClient()

print(f"⏳ Waiting for app '{app_name}' to come online (max 5 minutes)...")
for i in range(30):
    try:
        app = w.apps.get(name=app_name)
        state = getattr(app, "state", "UNKNOWN")
        url = getattr(app, "url", None)
        print(f"   [{i*10}s] state: {state}, url: {url}")
        if state == "RUNNING" and url:
            print(f"✅ App is running at {url}")
            break
    except Exception as e:
        print(f"   [{i*10}s] error: {e}")
    time.sleep(10)
else:
    print(f"❌ App never reached RUNNING state")
    print("   HINT: Re-check the source_code_path in databricks.yml and re-deploy.")

# COMMAND ----------

# ────────────────────────────────────────────────────────────────────────────
# SECTION 4: Smoke-test the app
# ────────────────────────────────────────────────────────────────────────────
# Hit the app's URL to confirm it serves a valid response. This query also
# shows up in system.query.history — which is what the validation query
# `app_query_logged` checks.

if "url" in dir() and url:
    try:
        resp = requests.get(url, timeout=10)
        print(f"✅ App responded with HTTP {resp.status_code}")
    except Exception as e:
        print(f"❌ App smoke test failed: {e}")

# COMMAND ----------

# ───────────────────────────────���────────────────────────────────────────────
# ✅ NOTEBOOK STATUS: BROKEN — Wrong source_code_path in DAB yml
# ────────────────────────────────────────────────────────────────────────────
# WHAT'S BROKEN:
#   The DAB yml has source_code_path: ./src/app.py
#   Streamlit expects app.py at the root of source_code_path.
#
# TO FIX:
#   Edit src/content/field-ops/medtech-research/bundle/databricks.yml:
#     apps:
#       medtech_rag_app:
#         source_code_path: ./app     # ← was ./src/app.py
#
#   Then re-deploy from your terminal:
#     databricks bundle deploy --target dev \
#       --var catalog=<your-catalog> --var schema_prefix=dbsword_medtech
#
# CONCEPTS LEARNED:
#   1. Databricks Apps: containerized web apps hosted by Databricks
#   2. source_code_path must point to a directory with app.py at its root
#   3. Free Edition: 3 apps max, auto-stop after 24h
#   4. Validation checks system.query.history for app queries
#
# MISSION COMPLETE when the app reaches RUNNING state and validation
# `app_query_logged` returns >= 1 row! 🏆
# ────────────────────────────────────────────────────────────────────────────